Vagrant.configure(2) do |config|
	config.vm.box = "miniarch-test"
	config.vm.hostname = "miniarch"
	config.vm.network "private_network", ip:"10.20.30.40"
	config.vm.provider "virtualbox" do |vbox|
		vbox.gui = true
		vbox.cpus = 1
		vbox.memory = "500"
	end
end
