Vagrant.configure(2) do |config|
	config.vm.box = "archmini-test"
	config.vm.hostname = "whatever"
	config.vm.network "private_network", ip:"10.20.30.40"
	config.vm.provider "virtualbox" do |vb|
		vb.gui = true
		vb.cpus = 1
		vb.memory = "200"
	end
end
